name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install OCaml and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ocaml ocaml-native-compilers opam

      - name: Initialize OPAM
        run: |
          opam init --disable-sandboxing -y
          eval $(opam env)

      - name: Install build tools
        run: |
          opam install dune --yes
          eval $(opam env)

      - name: Install dependencies
        run: |
          opam install js_of_ocaml js_of_ocaml-ppx --yes
          opam install . --deps-only --yes

      - name: Build web demo
        run: |
          dune build web/fable_web.bc.js

      - name: Prepare files for deployment
        run: |
          mkdir -p deploy
          cp web/index.html deploy/
          cp _build/default/web/fable_web.bc.js deploy/
          cp _build/default/web/fable_web.bc.js.map deploy/ 2>/dev/null || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages 