name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ocaml/opam:ubuntu-22.04-ocaml-4.14
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          opam install . --deps-only --yes

      - name: Build web demo
        run: |
          dune build web/fable_web.bc.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/default/web
          branch: gh-pages 