name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Create web files
        run: |
          mkdir -p deploy
          echo '<!DOCTYPE html>
          <html>
          <head>
              <title>Fable - Interactive Storytelling DSL</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
                  .container { max-width: 800px; margin: 0 auto; }
                  h1 { color: #2c3e50; }
                  .demo { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 5px; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Fable - Interactive Storytelling DSL</h1>
                  <div class="demo">
                      <h2>Coming Soon!</h2>
                      <p>We are working on bringing the interactive demo to the web. Stay tuned!</p>
                  </div>
              </div>
          </body>
          </html>' > deploy/index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          clean: true 